### ISSUE TITLE
SimpleLFO copy construction doesn't work

### ISSUE THREAD

**Issue by Xenakios** [surge-synthesizer/sst-basic-blocks#10]
sst::basic_blocks::modulators::SimpleLFO can't be copied (and possibly moved) correctly as a value because of the way the code has been written. Because that probably usually is not needed anyway, might be easiest to just delete the copy and move constructors/assignments for the class.

**Comment by baconpaul** [comment]
The cpi isn’t needed. Just add https://github.com/surge-synthesizer/sst-basic-blocks/blob/9c6f15c1c42599a6f5913ba94963676f94c845f0/CMakeLists.txt#L21 to the library target on windows
