### ISSUE TITLE
ParamMetaData::valueFromString should take in a FeatureState too and use it?

### ISSUE THREAD

**Issue by Xenakios** [surge-synthesizer/sst-basic-blocks#75]
Currently it is not possible for example to extend a parameter's range and convert a string to a value if the string has a valid value that is in the extended range. I am not sure if this is designed to work like this on purpose, but I guess it's more like a missing implementation at the moment in the ParamMetaData valueFromString method?

**Comment by baconpaul** [comment]
That is a missing implementation indeed I bet 

im in there early this week. Lemme peek

**Comment by baconpaul** [comment]
OK it's added at the head of code. I added a test also to make sure.

Extended only makes sense really in the float linear sense so that's where I supported it. We can think about the other modes too I suppose one day!
