### ISSUE TITLE
Curious issue with the Lanczos resampler

### ISSUE THREAD

**Issue by Xenakios** [surge-synthesizer/sst-basic-blocks#82]
It looks like zero initing the input array in the constructor with 
`
memset(input, 0, 2 * BUFFER_SZ * sizeof(float));
`
does not work correctly, at least on Windows/Clang 16.0.5. Junk is left in the input buffer, causing corrupted output during the first processing round.

Changing to the following seems to fix :

`memset(input[0], 0, BUFFER_SZ * sizeof(float));
memset(input[1], 0, BUFFER_SZ * sizeof(float));`

**Comment by baconpaul** [comment]
Oh yes that's definitely correct. Thank you. let me push a test and a change for that.

**Comment by baconpaul** [comment]
OK pushed a fix!

**Comment by Xenakios** [comment]
Thanks! My own fix proposal was of course also wrong, but happened to work for in my current set up. :)

**Comment by baconpaul** [comment]
Ha I wasn’t going to say anything :)
